version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - VITE_CORS_ORIGIN=https://api.reserse.id,https://flow.reserse.id,https://app.reserse.id,http://localhost:8000
    command: npm run dev
    networks:
      - app_network

  pgvector:
    image: phidata/pgvector:16
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai 
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgvolume: 