version: '3.8'

name: penyidik-toolkit-dev

services:
  frontend:
    build: .
    container_name: penyidik-frontend
    network_mode: "host"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    restart: "no"
    healthcheck:
      disable: true

volumes:
  app-data: {}

networks:
  app-network:
    driver: bridge 