version: '3.8'

name: penyidik-toolkit-dev

services:
  frontend:
    build: .
    container_name: penyidik-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://api.reserse.id
    healthcheck:
      disable: true
    labels:
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Frame-Options=DENY"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"

volumes:
  app-data: {}

networks:
  app-network:
    driver: bridge 