version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - HOST=0.0.0.0
    networks:
      - app_network
    depends_on:
      - pgvector

  pgvector:
    image: phidata/pgvector:16
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai 
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgvolume: 