version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 