version: '3.8'

name: penyidik-toolkit-dev

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: penyidik-frontend
    container_name: penyidik-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

volumes:
  app-data: {}

networks:
  app-network:
    driver: bridge 